### ISSUE TITLE
How to compile the project

### ISSUE THREAD

**Issue by j4cobgarby** [MichaelTheShifter/Memphis2#5]
When I import the VS project into Visual Studio 2017 and press the `Start` button, I get a dialog box saying:

> A project with an output type of class library cannot be started directly. _[...]_

How am I supposed to compile the project to test it, then?
It would also be nice to package a bootable .iso file with the source code

**Comment by mihail-mojsoski** [comment]
You need to install the Cosmos Development Kit.

**Comment by j4cobgarby** [comment]
Okay, thanks. Out of interest though, why is that?

**Comment by MichaelTheShifter** [comment]
Memphis is built using the Cosmos devkit, albeit an older version from
before they did all the netcore stuff.

So, in order to compile and use Memphis you need to have Cosmos dev kit
installed so all the libraries as well as the Visual Studio extension are
there for the compiler to use. Cosmos in fact uses its own compiler to
compile the MSIL code that comes in the form of a .dll or .exe file into
assembler code, which then gets put through NAsm to compile to machine code
which gets packed into an iso along with the syslinux bootloader.

This CANNOT be done with regular MSBuild, thus Cosmos is required. Also,
once you have Cosmos installed, be sure to set the MemphisBoot project as
your startup project before compiling. This is the project that makes
Cosmos do its thing.

**Comment by j4cobgarby** [comment]
thanks, i'll have a look at it then
